% -------------------------------------------------------------------------
% runBootstrapsCOCO.m
% -------------------------------------------------------------------------
% NOTE: Requires cluster, otherwise it would be too expensive
FUNCTIONS   = 1:24;
DIMENSIONS  = [2 3 5 8 10 20 40 60 100];
SAMPLE_SIZE = 100.*round(logspace(2,4,11)./100);
CLUST_PATH  = '/data/project1/pMelb0175/elaRobustness/';

for i=FUNCTIONS
    for j = 1:length(DIMENSIONS)
        for k = 1:length(SAMPLE_SIZE)
            script = ['#! /bin/sh \n',...
                              '#PBS -N bootELA_F' num2str(i)...
                              'D' num2str(DIMENSIONS(j)) ...
                              'C' num2str(SAMPLE_SIZE(k)) '\n',...
                              '#PBS -l walltime=12:00:00 \n',...
                              '#PBS -q fast \n',...
                              '#PBS -l nodes=1:ppn=12 \n',...
                              'cd  ' ...
                              CLUST_PATH '\n',...
                              'module load matlab \n',...
                              'matlab -nodisplay -r ' ...
                              '"clear all; '...
                              'delete(gcp(''nocreate'')); ' ...
                              'myPool = parpool(10); ' ...
                              'collectBootstrapsELA('...
                              num2str(i) ',' ...
                              num2str(DIMENSIONS(j)) ',' ...
                              num2str(SAMPLE_SIZE(k)) '); ' ...
                              'delete(myPool); ' ...
                              'exit;"'];

            filename = ['pbsScript_C' num2str(k) '.sh'];
            fid = fopen(filename,'w');
            fprintf(fid,script);
            fclose(fid);
            eval(['!qsub ' filename]);
        end
    end
end